export const FETCH_MOVIE = 'FETCH_MOVIE';
export const FETCH_MOVIE_IS_LOADING = 'FETCH_MOVIE_IS_LOADING';
export const FETCH_MOVIE_HAS_ERRORED = 'FETCH_MOVIE_HAS_ERRORED';

export const FETCH_DISCOVER_MOVIES = 'FETCH_DISCOVER_MOVIES';
export const FETCH_DISCOVER_MOVIES_IS_LOADING =
  'FETCH_DISCOVER_MOVIES_IS_LOADING';
export const FETCH_DISCOVER_MOVIES_HAS_ERRORED =
  'FETCH_DISCOVER_MOVIES_HAS_ERRORED';
